version: 2
updates:
  - directory: /ouroboros
    package-ecosystem: pip
    schedule:
      interval: monthly
    target-branch: dev
    groups:
      azure:
        patterns:
          - "azure*"
      pydantic:
        patterns:
          - "pydantic*"

  - directory: .github/workflows
    package-ecosystem: github-actions
    schedule:
      interval: monthly

