name: CI Client

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'client/**'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'client/**'

concurrency:
  group: ci-client-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check for typos
        uses: crate-ci/typos@v1.24.5

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        working-directory: ./client
        run: bun i

      - name: Run linter
        working-directory: ./client
        run: bun eslint
